# This is a basic workflow to build robot code.

name: SimulateJava

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch.
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "sim"
  sim:
  
    # Runs a single command using the runners shell
    - name: Runs the robot code in a simulator
      run: ./gradlew simulateJava